version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: integrados-pg
    environment:
      POSTGRES_USER: integrados_user
      POSTGRES_PASSWORD: integrados_password
      POSTGRES_DB: integrados_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
